### ISSUE TITLE
Ddt is uninstallable because of dep on License::Software:ver<0.2.0>

### ISSUE THREAD

**Issue by patrickbkr** [kalkin/Ddt#10]
Latest Ddt depends on License::Software:ver<0.2.0>. But License::Software does not have versioned entries in the ecosystem. So only the latest version (0.3.0) is available. This makes it impossible to install Ddt currently.

**Comment by kalkin** [comment]
Thank you for bringing this to my attention. Fix is on it's way.

**Comment by patrickbkr** [comment]
@kalkin Can this now be closed?
