### ISSUE TITLE
Change Description

### ISSUE THREAD

**Issue by zoffixznet** [kalkin/Ddt#2]
The META description states this distribution is a "replacement for mi6". However, you're neither the author of mi6 nor is mi6 abandoned. 

IMO such description is hostile and [it's actively causing confusion for users of mi6](https://irclog.perlgeek.de/perl6/2017-02-21#i_14135108).

**Comment by kalkin** [comment]
You are right fixed it.

**Comment by kalkin** [comment]
Sorry just noticed that while I changed the GitHub description, I haven't pushed the commit.
